Repository AxonFramework/IdeaPlugin, pull requests merged in 2022-02, with the labels that each got.

#20 Fine-tune the plugin description
  src/main/resources/META-INF/plugin.xml
Labels: Type: Enhancement, Status: In Progress, Priority 4: Would

#24 Fix inspection descriptions, fixes #21
  src/main/resources/META-INF/plugin.xml
Labels: Type: Bug, Status: In Progress, Priority 2: Should

#26 Fix wrong icon being shown for Publishers in popup
  CHANGELOG.md
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/creators/DefaultMessageCreator.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/QueryHandler.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommandHandlerMethodLineMarkerProviderTest.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommonHandlerMethodLineMarkerProviderTest.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/DeadlineHandlerMethodLineMarkerProviderTest.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/markers/publishers/PublishMethodLineMarkerProviderTest.kt
Labels: Type: Bug, Status: In Progress, Priority 2: Should

#25 Automatic releasing
  .github/dependabot.yml
  .github/workflows/pluginverifier.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  build.gradle.kts
  gradle.properties
  src/main/kotlin/org/axonframework/intellij/ide/plugin/inspections/aggregate/JavaAggregateIdInspection.kt
  src/main/resources/META-INF/plugin.xml
Labels: Type: Enhancement, Status: In Progress, Priority 1: Must

#33 Recommend plugin when Axon Framework is found in project
  CHANGELOG.md
  gradle.properties
  src/main/resources/META-INF/plugin.xml
Labels: Type: Enhancement, Status: In Progress, Priority 1: Must
