Repository AxonFramework/IdeaPlugin, pull requests merged in 2022-07, with the labels that each got.

#108 PR for issue / feature #107
  src/main/kotlin/org/axonframework/intellij/ide/plugin/util/ProjectUtils.kt
Labels: Priority 1: Must

#114 Use property for Axon Framework version test dependency
  build.gradle.kts
  gradle.properties
Labels: Priority 2: Should

#115 Add method consideration to Aggregate ID inspection
  src/main/kotlin/org/axonframework/intellij/ide/plugin/api/Entity.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/inspections/aggregate/JavaAggregateIdInspection.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/inspections/aggregate/KotlinAggregateIdInspection.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/inspections/aggregate/descriptions.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/AggregateStructureResolver.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/util/PSiProcessingUtils.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/inspections/aggregate/JavaAggregateIdInspectionTest.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/inspections/aggregate/KotlinAggregateIdInspectionTest.kt
Labels: Type: Bug, Priority 2: Should

#117 Fix various issues found in sentry
  gradle.properties
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/AxonNavigationGutterIconRenderer.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/ClassLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/AbstractHandlerLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommandHandlerMethodLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommandInterceptorLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommonHandlerMethodLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/DeadlineHandlerMethodLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/ValidatingLazyValue.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/publishers/DeadlinePublisherLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/publishers/PublishMethodLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/AnnotationResolver.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/support/ReportingService.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/usage/AxonVersionService.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/util/PSiProcessingUtils.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/util/ProjectUtils.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/axonframework/intellij/ide/plugin/util/ProjectUtilsKtTest.kt
Labels: Type: Bug, Type: Enhancement, Priority 2: Should
