Repository AxonFramework/IdeaPlugin, pull requests merged in 2024-10, with the labels that each got.

#288 Migrate to plugin v2 and fix compatibility with new EAP IDEA version …
  .github/workflows/publish.yml
  .github/workflows/qodana.yml
  .github/workflows/test.yml
  .gitignore
  CHANGELOG.md
  build.gradle.kts
  gradle.properties
  src/main/kotlin/org/axonframework/intellij/ide/plugin/api/AxonAnnotation.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/api/Handler.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/api/MessageHandlerType.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/publishers/DeadlinePublisherLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/AnnotationResolver.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/searchers/CommandHandlerInterceptorSearcher.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/searchers/CommandHandlerSearcher.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/searchers/DeadlineHandlerSearcher.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/searchers/EventHandlerSearcher.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/searchers/EventSourcingHandlerSearcher.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/searchers/QueryHandlerSearcher.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/searchers/SagaEventHandlerSearcher.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/AggregateConstructor.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/CommandHandler.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/CommandHandlerInterceptor.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/DeadlineHandler.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/EventHandler.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/EventSourcingHandler.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/QueryHandler.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/SagaEventHandler.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/usage/AxonImplicitUsageProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/usage/AxonVersionService.kt
Labels: Type: Enhancement, Status: In Progress, Priority 1: Must

#289 Add renderers to class-level popups so they are rendered correctly
  CHANGELOG.md
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/ClassLineMarkerProvider.kt
Labels: Type: Bug, Status: In Progress, Priority 1: Must

#290 Take class hierarchy into account when resolving
  CHANGELOG.md
  src/main/kotlin/org/axonframework/intellij/ide/plugin/api/MessageHandlerType.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommandHandlerMethodLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommandInterceptorLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommonHandlerMethodLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/markers/publishers/PublishMethodLineMarkerProvider.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/MessageCreationResolver.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/MessageHandlerResolver.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/searchers/CommandHandlerInterceptorSearcher.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/resolving/handlers/types/CommandHandlerInterceptor.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/util/PSiProcessingUtils.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/axonframework/intellij/ide/plugin/handlers/searchers/CommandHandlerInterceptorSearcherTest.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommandHandlerMethodLineMarkerProviderTest.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/markers/handlers/CommandInterceptorLineMarkerProviderTest.kt
Labels: Type: Enhancement, Status: In Progress, Priority 2: Should

#306 [#307] Axon plugin gives false highlights about non existing properties when they are defined in a superclass
  src/main/kotlin/org/axonframework/intellij/ide/plugin/inspections/saga/JavaSagaAssociationPropertyInspection.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/inspections/saga/KotlinSagaAssociationPropertyInspection.kt
  src/main/kotlin/org/axonframework/intellij/ide/plugin/util/PSiProcessingUtils.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/inspections/saga/JavaSagaAssociationPropertyInspectionTest.kt
  src/test/kotlin/org/axonframework/intellij/ide/plugin/inspections/saga/KotlinSagaAssociationPropertyInspectionTest.kt
Labels: Type: Bug, Status: In Progress, Priority 2: Should
